--- # This will install the tomcat and its dependices in the testserver.

- hosts: testserver
  vars:
    java: java-1.8.0-openjdk-devel   

  tasks:

  - name: To createa a group
    group:
      name: tomcat
      state: present
      
  - name: To create a user
    user:
      name: tomcat
      state: present
      group: tomcat

  - name: To create a directory for logs
    file:
      path: /opt/apache_logs
      state: directory
      owner: tomcat
      group: tomcat
      mode: 0644
     
  - name: Install dependency
    yum:
      name: '{{ java }}'
      state: installed
 
  - name: To download the archive
    get_url:
      url: http://mirrors.estointernet.in/apache/tomcat/tomcat-8/v8.5.39/bin/apache-tomcat-8.5.39.tar.gz
      dest: /opt/apache-tomcat-8.5.39.tar.gz
      

  - name: To untar and unzip the archive
    unarchive:
      src: /opt/apache-tomcat-8.5.39.tar.gz
      dest: /opt
      mode: 0755
      remote_src: yes

  - name: To install the git
    yum:
      name: git
      state: installed

  - name: To checkout the code
    git:
      repo: 'https://github.com/gouthamchilakala/PetClinic.git'
      dest: /opt/Petclinic   

  - name: to start the tomcat
    command: nohup /opt/apache-tomcat-8.5.39/bin/startup.sh &
